"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

new_sum,old_sum,even_valued,fib=1,0,0,0

while(fib<4000000):
  fib=new_sum+old_sum
  if fib%2==0:
    even_valued+=fib
  old_sum=new_sum
  new_sum=fib

print(even_valued) #4613732
